### PR TITLE
add osfingermap and Debian11

### PR DESCRIPTION
**Pull request by jnijdam**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Review by myii — APPROVED** [review]

**Comment by myii** [comment]
Merged, thanks for the PR, @jnijdam.

**Comment by jnijdam** [comment]
Sorry but i found a mistake in map.jinja line 15 ("osfinger", osfingermap) and not ("osfinger", osfingermapmap),
Very sorry about that, do you want an other PR to fix it ?

**Comment by daks** [comment]
@jnijdam yes, please submit a new PR to fix that

**Comment by myii** [comment]
> Sorry but i found a mistake in map.jinja line 15 ("osfinger", osfingermap) and not ("osfinger", osfingermapmap), Very sorry about that, do you want an other PR to fix it ?

@jnijdam Yes, please.  Usually our CI will catch that out but there's none for this formula yet.

**Comment by daks** [comment]
@myii yes it's missing versioning at least, plus some tests. Debian 11 didn't work before this PR for example

**Pull request merged**
